import {
  DEFAULT_CHARACTER_PROFILE_ID,
  DEFAULT_VILLAGER_PROFILE_ID,
} from '@shared/characterAnimation';

export const DEFAULT_PLAYER_PROFILE_ID = DEFAULT_CHARACTER_PROFILE_ID;
export const DEFAULT_NPC_PROFILE_ID = DEFAULT_VILLAGER_PROFILE_ID;
